### ISSUE TITLE
desperate, ive been robbede and had my kids taken away with lies.... need disabled vet needs help.

### ISSUE THREAD

**Issue by RcG3173** [yuchestart/Contact-Me#1]
is:open is anyone willing to get me info on a current phone number as well as the number had b4... is that even possible? im out of time im just not getting anywhere.... the current number is 951-557-3107 former number is 951-801-0825. i need text phone logs and social media to prove she was cheating for last year atleast,,,, maybe longe4r. really would like to see her myspace just found out about after 10yrs

**Comment by yuchestart** [comment]
Ma'am/Sir, this is an issues channel, not a channel to settle your personal troubles. The issues channel is for technical problems. This is a prank page redirecting to a rickroll, not a redirect to myspace. This webpage has been designed to fake a myspace webpage by copying certain `<meta>` tags on the normal myspace page. I do not have a myspace account. I recommend posting this somewhere else, as GH Issues isn't the right place for it.
